# Generated by Django 5.2.2 on 2025-06-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_by_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generated_add',
            field=models.TextField(blank=True, null=True),
        ),
    ]
